### ISSUE TITLE
Error to fetch scope. What is the issue?

### ISSUE THREAD

**Issue by moekify** [wearefine/slack-archive-bot#3]
✓ Fetching Slack channels
✖ Error fetching channel undefined with error: Error: missing_scope

/home/mirko/.config/yarn/global/node_modules/slack-archivebot/index.js:137
        if (moment.duration(now - data.messages[0].ts, 's').asDays() > inactiveDays) {
                                       ^

TypeError: Cannot read property 'messages' of undefined
    at slack.channels.history (/home/mirko/.config/yarn/global/node_modules/slack-archivebot/index.js:137:40)
    at _res (/home/mirko/.config/yarn/global/node_modules/slack/methods/_exec.js:39:7)
    at IncomingMessage.__end (/home/mirko/.config/yarn/global/node_modules/tiny-json-http/_write.js:75:9)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by moekify** [comment]
Changing data.messages[0].ts to data.latest seemed to have fixed the issue. I think the method changed / was depreciated.

EDIT: Nevermind, archiving doesn't work. I'll investigate further

**Comment by cpitkin** [comment]
@moekify Thanks for the update and for using the project. I am looking at the API and code now to determine where the bug may have been introduced.

**Comment by cpitkin** [comment]
@moekify Try the master branch now and see if you get the same error. The changes that you make on the date checking won't work. The channels.history [documentation](https://api.slack.com/methods/channels.history) says that value is just to get the latest message and is set to `now()` by default. If you're still getting the scope error then it may be something with the token you're using. Slack tokens are scoped and it referenced in the documentation above.

**Comment by moekify** [comment]
@cpitkin There was no update to the repository? So unfortunately still not working. I added the channels.history to the token of course :) 

EDIT: Just saw that the branch was just not merged with master :) I'll checkout the branch
